---
connectors:
- connector_name: slack
  fields:
    channelidentifier: C015LGE7RRQ
    bearertoken: xoxb-538932482230-1196713168180-w9fbEVDahD3dC7gTwcA85jHd
---
buildbreaker:
- activityname: sast
  status:
  - new
  - open
  overallseverity:
  - high
  categories:
  - name: Stored Cross-site Scripting(XSS)
    severity: medium
  - name: sql-injection
    severity: low
- activityname: dast
  status:
  - new
  - triaged
  overallseverity:
  - high
  categories:
  - name: Sql-Injection
    severity: medium
- activityname: sca
  status:
  - new
  overallseverity:
  - high
  categories:
  - name: cve-2015-2119
    severity: medium
---
tool_information:
- tool_name: blackduck
  enabled: true
  fields:
    project_name: insecure-bank
    project_version: 1.0.0
    instance_url: https://bizdevhub.blackducksoftware.com
    auth_token: ODM3YjE3YTUtMmM4YS00M2UyLWE2YmYtNjYyNTNhODJmZGNkOmI0Njk1ODRmLTc0NWItNDkxZS1iYTdmLTEzODRmOTIxYzBhYw==
- tool_name: polaris
  enabled: true
  fields:
    project_name: insecure-bank
    instance_url: https://csprod.polaris.synopsys.com
    auth_token: erbsrhcmj513j678hil89j5nsesqfvventnj8o9gin0l9stmjv20